[application]
name = "ChronoCherish"
default_platform = "desktop"
asset_dir = "assets"
out_dir = "dist"

[web.app]

# HTML title tag content
title = "ChronoCherish"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "work.changsun.www"
publisher = "@changsun20"
icon = ["assets/icons/icon.ico"]
resources = ["./assets"]

[bundle.windows]
tsp = false
webview_install_mode = "Skip"
allow_downgrades = true
icon_path = "assets/icons/icon.ico"

[bundle.windows.nsis]
installer_icon = "assets/icons/icon.ico"
languages = ["SimpChinese", "English"]
install_mode = "CurrentUser"
display_language_selector = true
