[application]
name = "ChronoCherish"
default_platform = "desktop"
asset_dir = "assets"
out_dir = "dist"

[web.app]

# HTML title tag content
title = "ChronoCherish"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "work.changsun.www"
publisher = "@changsun20"
icon = ["assets/icons/chrono-cherish-icon.ico"]
resources = ["assets/css/tailwind.css"]
